### ISSUE TITLE
Overlapping

### ISSUE THREAD

**Issue by jaja43439** [jahongir7174/YOLOv5-tf#14]
How should I solve the problem of bounding box overlapping?
I tried the non_max_suppression function, but it seems not work.

**Comment by jahongir7174** [comment]
you can change the following variables for your purpose:
- [box threshold](https://github.com/jahongir7174/YOLOv5-tf/blob/ea02a297b39b902fe535eda1a87997a2f7db1419/utils/config.py#L10) that is used [here](https://github.com/jahongir7174/YOLOv5-tf/blob/ea02a297b39b902fe535eda1a87997a2f7db1419/nets/nn.py#L165)
- [nms IoU threshold](https://github.com/jahongir7174/YOLOv5-tf/blob/ea02a297b39b902fe535eda1a87997a2f7db1419/nets/nn.py#L170), it is 0.1 by default
