### ISSUE TITLE
width and depth parameters in the config.py

### ISSUE THREAD

**Issue by Arunavameister** [jahongir7174/YOLOv5-tf#15]
Hello, Firstly, thank you for making this repo public.
Can you explain the height and the width parameters in the config.py? What do they represent?
Also, how did you choose the constant values for them?
Thanks

**Comment by jahongir7174** [comment]
original yolov5s has [these](https://github.com/ultralytics/yolov5/blob/b60b62e874e7cf0581c51936e39287c6906a419f/models/yolov5s.yaml#L3) configuration
