### ISSUE TITLE
Lack of other versions

### ISSUE THREAD

**Issue by XiaoXiLe2023** [jahongir7174/YOLOv5-tf#2]
Hello, thanks for your sharing of your work.

In pytorch version, there are four versions: s, m, l, x.

By viewing your code, I guess your network is yolov5x.

Do you have plans of updating the other version like s?

Thanks a lot

**Comment by XiaoXiLe2023** [comment]
I replaced the parameters of classes of network modules in nn.py with the  parameters of yolov5s and started training successfully.
I'll validate whether the training result is right.

**Comment by jahongir7174** [comment]
hello, thanks for your interest.
yes, this is x version.
i will reorganize the repo to support other versions

**Comment by jahongir7174** [comment]
other versions are added
