### ISSUE TITLE
bug report about util.resize

### ISSUE THREAD

**Issue by XiaoXiLe2023** [jahongir7174/YOLOv5-tf#3]
Hello,jahongir7174.

util.resize returns image_padded, scale, dw, dh.

However, in test.py, at about line 46, image_np, dw, dh, scale = util.resize(image_np).

Please fix the bug. Thanks for your job again.

**Comment by jahongir7174** [comment]
I fixed the issue
thank you for informing me about the bug.

**Comment by aidevveloper** [comment]
Do'stim omad ishlarga. Custom dataset uchun ham codelarizni moslab repoga qo'shib qo'ying. Men ham foydalanaman

**Comment by jahongir7174** [comment]
LabelMe annotation tool dan foydalansangiz bo'ladi do'stim. PascalVOC bilan bir xil qilib annotate qiladi

**Comment by aidevveloper** [comment]
Thank you my teacher)
