### ISSUE TITLE
Can you provide an example of dataset structure?

### ISSUE THREAD

**Issue by marcusdiy** [jahongir7174/YOLOv5-tf#6]
Hi, I'm new to AI and I'm trying to make train my own dataset but i have difficulties understanding how to organize and label data.
Can you actually create the "Dataset folder" with a couple of images (and related train.txt, etc) inside that I can use as example?
Thant way I think will be able change my data as per your project structure. 
Thanks!

**Comment by jahongir7174** [comment]
Hello, you can refer VOC dataset for reference (http://host.robots.ox.ac.uk/pascal/VOC/voc2012/index.html#devkit)
I have attached a file that contains a sample dataset.
[Dataset.zip](https://github.com/jahongir7174/YOLOv5-tf/files/5881011/Dataset.zip)

**Comment by marcusdiy** [comment]
@jahongir7174 Thanks! That will do. Have a nice day 👋
