### ISSUE TITLE
some issue

### ISSUE THREAD

**Issue by cslee99** [jahongir7174/YOLOv5-tf#7]
It works well, but sometimes it freezes and doesn't work.
It is displayed and stops as shown in the execution log below. And it cannot create the TF folder.
However, it works normally after a few attempts. Do you have any idea of a solution to the issue?

Execution log
mcrc-ml@mcrcml-DGX-Station:~/workspace/cslee/YOLOv5-tf$ python generate.py
2021-02-04 17:41:11.943521: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
/home/mcrc-ml/anaconda3/envs/tf230/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3334: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/mcrc-ml/anaconda3/envs/tf230/lib/python3.8/site-packages/numpy/core/_methods.py:153: RuntimeWarning: invalid value encountered in true_divide
  ret = um.true_divide(

**Comment by jahongir7174** [comment]
thank you for your report.
1.this issue is related to anchor generation and randomness (https://github.com/jahongir7174/YOLOv5-tf/blob/356e16e49e0ce8f71234e4947d0ca60ef2fa6e00/generate.py#L51)
2. repo uses Keras data generator as data loader by default, if you generate anchors successfully, you can update anchors in config.py and generate tf_record.

**Comment by cslee99** [comment]
한국분이시죠?
Yolo 사용하기 쉽게 너무 잘 개발된거 같습니다.
피드백 감사드립니다.
적용해 보도록 하겠습니다.

2021년 2월 4일 (목) 오후 9:59, jahongir7174 <notifications@github.com>님이 작성:

**Comment by jahongir7174** [comment]
feel free to open an issue if any problem arises.

**Comment by cslee99** [comment]
Other packages are inconvenient to use, but the YOLOv5 package you developed is very comfortable to use, so I am very grateful.
This is a continuing question related to the above question.
The cluster is being created normally.
Maybe the problem below is the cause.
It is okay when the TF folder is created normally.
However, there is a problem with an infinite loop in the while inside the generator function.
Is there any way to solve it so that it always works normally?

**Comment by jahongir7174** [comment]
if you generated TF folder and tf_record, it uses https://github.com/jahongir7174/YOLOv5-tf/blob/356e16e49e0ce8f71234e4947d0ca60ef2fa6e00/utils/dataset.py#L61 data loader by checking https://github.com/jahongir7174/YOLOv5-tf/blob/356e16e49e0ce8f71234e4947d0ca60ef2fa6e00/train.py#L26
can you debug the code and verify which data loader is being used?

**Comment by mozeqiu** [comment]
hello jahongir.thanks you code.But something went wrong when I used it。when i run generate.py,it work good but just generate anchors no tf and Anything else。
 `K anchors:
 [[  9.   9.]
 [ 15.  15.]
 [ 19.  21.]
 [ 24.  32.]
 [ 26.  25.]
 [ 33.  35.]
 [ 44.  48.]
 [ 62.  77.]
 [105. 165.]]
Accuracy: 77.75%
`

**Comment by jahongir7174** [comment]
you can train the network without generating tf_record files. if you would like to use tf_record data loader, you may refer to this issue https://github.com/jahongir7174/YOLOv5-tf/issues/8#issuecomment-773863870

**Comment by jahongir7174** [comment]
I tested the default data loader in several machines, it works as expected. if you encounter any issue, feel free to submit the log

**Comment by cslee99** [comment]
I only need to do the Train.
Isn't TF-Record essential to run the train?
Can I train with IMAGES, LABELS, and train.txt?

**Comment by jahongir7174** [comment]
yes, you can train the network without generating tf_record files

**Comment by cslee99** [comment]
Thanks for the quick reply.
Do you have any options for train?
Only IMAGES, LABELS folders and train.txt files exist in the Dataset-COCO folder.
      (tf230) mcrc-ml@mcrcml-DGX-Station:~/workspace/cslee/YOLOv5-tf$  python train.py
An error occurs as shown below.
=========================== Error ===========================
Instructions for updating:
Use `tf.data.Iterator.get_next_as_optional()` instead.
Traceback (most recent call last):
  File "train.py", line 82, in <module>
    main()
  File "train.py", line 66, in main
    for step, inputs in enumerate(dataset):
  File "/home/mcrc-ml/anaconda3/envs/tf230/lib/python3.8/site-packages/tensorflow/python/distribute/input_lib.py", line 649, in __next__
    return self.get_next()
  File "/home/mcrc-ml/anaconda3/envs/tf230/lib/python3.8/site-packages/tensorflow/python/distribute/input_lib.py", line 706, in get_next
    global_has_value, replicas = _get_next_as_optional(self, self._strategy)
  File "/home/mcrc-ml/anaconda3/envs/tf230/lib/python3.8/site-packages/tensorflow/python/distribute/input_lib.py", line 548, in _get_next_as_optional
    iterator._iterators[i].get_next_as_list(new_name))  # pylint: disable=protected-access
  File "/home/mcrc-ml/anaconda3/envs/tf230/lib/python3.8/site-packages/tensorflow/python/distribute/input_lib.py", line 1494, in get_next_as_list
    data_list = self._iterator.get_next_as_optional()
  File "/home/mcrc-ml/anaconda3/envs/tf230/lib/python3.8/site-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py", line 601, in get_next_as_optional
    iterator_ops.get_next_as_optional(self._device_iterators[i]))
  File "/home/mcrc-ml/anaconda3/envs/tf230/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/mcrc-ml/anaconda3/envs/tf230/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 952, in get_next_as_optional
    gen_dataset_ops.iterator_get_next_as_optional(
  File "/home/mcrc-ml/anaconda3/envs/tf230/lib/python3.8/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2692, in iterator_get_next_as_optional
    _ops.raise_from_not_ok_status(e, name)
  File "/home/mcrc-ml/anaconda3/envs/tf230/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: ./Dataset/COCO/TF/1.tf; No such file or directory
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]] [Op:IteratorGetNextAsOptional]

**Comment by jahongir7174** [comment]
it is using tf_record data loader, the log shows that there is a TF folder, but it may not have the desired record files
https://github.com/jahongir7174/YOLOv5-tf/blob/356e16e49e0ce8f71234e4947d0ca60ef2fa6e00/train.py#L26
https://github.com/jahongir7174/YOLOv5-tf/blob/356e16e49e0ce8f71234e4947d0ca60ef2fa6e00/train.py#L33

**Comment by cslee99** [comment]
I was using the old version.
Both Train and Test work well.
It is very well developed and I am testing it comfortably.
Thank you for sharing the source code.

**Comment by jahongir7174** [comment]
okay, if it is solved, please close the issue. if you have any issue, you can open again
