### ISSUE TITLE
some issues about generate.py

### ISSUE THREAD

**Issue by mozeqiu** [jahongir7174/YOLOv5-tf#8]
hello jahongir.thanks you code.But something went wrong when I used it。when i run generate.py,it work good but just generate anchors no tf and Anything else。
K anchors: [[ 9. 9.] [ 15. 15.] [ 19. 21.] [ 24. 32.] [ 26. 25.] [ 33. 35.] [ 44. 48.] [ 62. 77.] [105. 165.]] Accuracy: 77.75%

**Comment by jahongir7174** [comment]
hello, thank you for your report.
training works without generating tf_record files. if you want to use the tf_record data loader, you need to generate tf_record files.
to generate tf_record files, first, generate anchors, and update anchors var in  config.py. second, call generate_tf_record() function after https://github.com/jahongir7174/YOLOv5-tf/blob/356e16e49e0ce8f71234e4947d0ca60ef2fa6e00/generate.py#L162 line

**Comment by mozeqiu** [comment]
Thank you for your reply, I found the problem and starting training。
Thanks again for your code 。god bless you
